### ISSUE TITLE
[ Wish ] Make terminal-plus use the global status bar

### ISSUE THREAD

**Issue by i90rr** [jeremyramin/terminal-plus#132]
Hi, could it be possible to use the global status bar as other terminal packages use (i.e 'terminal-panel')?
The goal would be to reduce interface clutter by minimizing new UI sections and to free some screen space.

**Comment by jeremyramin** [comment]
Yes, it could be possible. I'm working on having an option for this in the next release. Since this is a duplicate of issue #85, I'll be closing this in favor of that thread. Once I release a version with this feature, I will notify that thread. If you would like to be notified as well, please leave a message there.
