### ISSUE TITLE
Terminal does not work with IME

### ISSUE THREAD

**Issue by mathewv** [jeremyramin/terminal-plus#14]
On Linux with IBus/Anthy, it isn't possible to type Japanese characters in the terminal. Presumably other languages that require an IME also don't work, and I would assume the same problem exists on Windows and OS X.

**Comment by jeremyramin** [comment]
Thanks for reporting this. I'll look into it.

**Comment by jeremyramin** [comment]
I offer my sincerest apologies for taking so long to get back to you. I believe I have fixed this in the latest release (v0.7.0) of Terminal-Plus. If you could, please give it a try and let me know if your issue has been fixed.

**Comment by mathewv** [comment]
Thanks for getting back to me. Unfortunately the IME still doesn't work (i.e. converting typed Latin characters to Japanese characters) when typing in the terminal, although CJK characters do render properly in it.

**Comment by jeremyramin** [comment]
I might of misunderstood what the issue is. So the issue isn't for typing Japanese characters directly into the Terminal, but rather Latin characters converting to Japanese characters in the input field. I'm not entirely familiar with this process, but I get the feeling that the limitations of my package dependencies might make this hard to accomplish.

**Comment by mathewv** [comment]
Sorry if I wasn't clear enough in the OP, but yes, that's the issue. I hope it isn't too much trouble for you to implement, since I'm not familiar with what goes into making things compatible with IME software either.

**Comment by jeremyramin** [comment]
@mathewv I want to offer my apologies. I was not able to implement IME support directly inside of the terminal. However I believe I have found an alternative solution that hopefully is not to cumbersome to use.

Please take a look at v0.11.0 and the new `Insert Text` feature. There is a keyboard icon in the top left that presents an input box for you to type in. There I believe you should be able to do IME typing and other special key combinations. On confirm, the input box will dismiss and insert your text into the terminal. The input box can be keymapped with the `terminal-plus:insert-text` command. Hopefully this works for you and solves your issue.

**Comment by abrar2741** [comment]
@jeremyramin Awesome! I don't type Japanese but still your approach is truly awesome. Now I came to know why that different dialog box for typing was present. 

Hello, I am Abrar Shaikh and am new to programming and have started with python. Would you guide me how to use your terminal plus. I can run the code using Code Runner package and normal windows terminal but when I do the same it shows this error:

![fix terminal 1](https://cloud.githubusercontent.com/assets/15705845/11021305/6caff78e-8663-11e5-8e0b-447c2142ec07.png)

Also, this happens when I try to change directory.
'Change directory' to previous folder works properly:   cd..
But 'change directory' to next folder does not work: cd Week 2

![fix terminal 2](https://cloud.githubusercontent.com/assets/15705845/11021319/e550b638-8663-11e5-9710-9f48482d3f76.png)

Do I have to make any additional changes in Terminal Plus? Please reply soon...

**Comment by jeremyramin** [comment]
@abrar2741 To run a python file you need to run it with the `python` command:
`python Assignment2_1.py`

>Also, this happens when I try to change directory.
'Change directory' to previous folder works properly: cd..
But 'change directory' to next folder does not work: cd Week 2

When you change directories to a folder with a space in the name, you need to escape the space or put quotes around it:
`cd Week\ 2` or `cd "Week 2"`

**Comment by jeremyramin** [comment]
As of v0.14.0, Terminal-Plus now supports IME character input. Please review the latest release and let me know what you think.

**Comment by mathewv** [comment]
Ah, sorry I didn't notice this earlier. I really appreciate that you took the time to implement this feature, thank you.
