### ISSUE TITLE
High scrolling speed in terminal window

### ISSUE THREAD

**Issue by brbrr** [jeremyramin/terminal-plus#31]
Scrolling speed is very high. it's definitely higher than my terminal app speed. 
both terminal app and terminal plus is using `/bin/bash`

Mac OS X 10.10.5
Atom 1.0.19
Terminal-plus 0.6.5

**Comment by jeremyramin** [comment]
Scrolling speed is definitely high but this is because the Terminal-Plus dependency handles scrolling manually. Rather than having all of your history present in Atom, there are only enough elements to fill the terminal view. These elements then just have their text adjusted as you "scroll". A draw-back is that we lose smooth scrolling which makes the terminal scroll appear fast.

**Comment by jeremyramin** [comment]
@brbrr Please give v0.8.0 a try, I attempted to implement finer scrolling. Hopefully, it is to your liking.

**Comment by brbrr** [comment]
@jeremyramin I've check 0.8.1. and it's much better. but I prefer slower speed if it's possible. but anyway - thanks!

**Comment by jeremyramin** [comment]
So I decided to try another algorithm in v0.8.2. Your feedback on the the scroll speed would be greatly appreciated. Sorry, I'm persistent.

**Comment by jeremyramin** [comment]
This issue has been fixed as of v0.8.2

**Comment by brbrr** [comment]
@jeremyramin Sorry, forgot to give a feedback. Now it's awesome, thanks!
