### ISSUE TITLE
not work with atom ver 1.9.9

### ISSUE THREAD

**Issue by ntd94** [jeremyramin/terminal-plus#331]
with my atom version 1.9.9, terminal-plus did not work. I can toggle, I can see status bar...

**Comment by skiner** [comment]
the same problem
<img width="795" alt="screenshot 2016-08-31 13 25 38" src="https://cloud.githubusercontent.com/assets/2145650/18125338/6f8660ce-6f7e-11e6-8f9e-5cfee8110912.png">

**Comment by chakrihacker** [comment]
I am also facing same problem, I tried uninstalling and installed fresh copy but doesn't work

**Comment by diazgilberto** [comment]
Same problem here.

**Comment by Dilan** [comment]
+1

**Comment by estebanutz** [comment]
+1

**Comment by sebfindling** [comment]
lucky you, i don't even get to see the status bar

**Comment by sebfindling** [comment]
same here :(

**Comment by FAST-JE** [comment]
+1 for v1.10.0

**Comment by smna15** [comment]
same for me too.

**Comment by ewized** [comment]
+1

**Comment by 3DEsprit** [comment]
It was working for me with 1.9.9 on Linux, but it was only after upgrading from an earlier version (1.9.6). I'm sure something carried over making an exception. As soon as I installed on a fresh install of 1.9.9, I had this exact problem as well. Even so, I did come across an issue when using my same atom package settings from settings-sync, as Atom complained that I had to rebuild terminal-plus, because it was using build 45 instead of 46. 

Anyways, I was able to copy the terminal-plus folder from the older install, and it now works on my latest install. I know, that's a horrible way to do it, but I can't live without this terminal. I'm happy to look at my now working install for anything to help find reasons why it's not working for fresh installs (both plugin installs were 0.14.5).

**Comment by smna15** [comment]
@3DEsprit I did what you did and it worked for me!

**Comment by chakrihacker** [comment]
@3DEsprit can you share the old build

**Comment by diazgilberto** [comment]
@3DEsprit it is a way to share the terminal-plus folder? Your story is mine, I did a clean install for my mac but I don't backup apps, so I can't go back a look for that settings.

**Comment by UltimatePancake** [comment]
+1

**Comment by xjchan** [comment]
+1

**Comment by ryanvade** [comment]
+1 1.10 ```Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.```

**Comment by devinus** [comment]
Same on Atom 1.10 on macOS 10.11.6 as well.

**Comment by 3DEsprit** [comment]
You should be able to get it working downloading 2.9.6, 2.9.7, installing terminal-plus, and then upgrading once you have a working terminal-plus (in theory). 

I think I found out what makes mine work. It is very possible one of the packages installed are breaking it. The versions in parens are those of the packages used in the working build, versus what apm is installing for 0.14.5 with 1.9.9:

`├─┬ atom-space-pen-views@2.2.0 
│ ├── fuzzaldrin@2.1.0 
│ └─┬ space-pen@5.1.2 
│   ├─┬ grim@1.5.0 
│   │ └─┬ emissary@1.3.3 
│   │   ├─┬ es6-weak-map@0.1.4 
│   │   │ ├── d@0.1.1 
│   │   │ ├─┬ es5-ext@0.10.12 (0.10.11)
│   │   │ │ ├── es6-iterator@2.0.0 (0.1.3)
│   │   │ │ └── es6-symbol@3.1.0 (2.0.1)
│   │   │ ├── es6-iterator@0.1.3 
│   │   │ └── es6-symbol@2.0.1 
│   │   ├── mixto@1.0.0 
│   │   └── property-accessors@1.1.3 
│   ├── jquery@2.1.4 
│   └─┬ underscore-plus@1.6.6 
│     └── underscore@1.6.0 
├─┬ pty.js@0.3.0  (git+https://github.com/jeremyramin/pty.js.git#28f26677e94b9ee7c7bf5cbdc698a45f0766b295)
│ ├── extend@1.2.1 
│ └── nan@2.0.5 
├── term.js@0.0.7  (git+https://github.com/jeremyramin/term.js.git#de1635fc2695e7d8165012d3b1d007d7ce60eea2)
└── underscore@1.8.3 `

I hope that helps someone get a working version, because it seems these packages are what make mine work. If I remove the node_modules, and rebuild, it breaks again.

**Comment by EQuimper** [comment]
+1

**Comment by lcsrinaldi** [comment]
+1 for 1.10.0

**Comment by graywithanA** [comment]
same issue here.

**Comment by graywithanA** [comment]
Replacing the existing files with those of an older version worked for me as well.  I've attached the files for anyone who wants em.  Be sure that you rename the folders after unzipping; they should both be named `terminal-plus`.

`apm/terminal-plus.zip` should be placed in `~/.atom/.apm` once unzipped and renamed to `terminal-plus`.

`packages/terminal-plus` goes in `~/.atom/packages` after unzip/rename.

[apm:terminal-plus.zip](https://github.com/jeremyramin/terminal-plus/files/452544/apm.terminal-plus.zip)
[packages:terminal-plus.zip](https://github.com/jeremyramin/terminal-plus/files/452545/packages.terminal-plus.zip)

**Comment by diazgilberto** [comment]
Thank you for the files.

**Comment by 3DEsprit** [comment]
@graywithanA Great to hear that worked out without a hitch! Did you change the git repos for term.js and pty.js as well, or just the es5-ext and it's deps?

**Comment by graywithanA** [comment]
Simply deleted the existing `terminal-plus` directories in the two locations mentioned and replaced them with the one's above.  That's it.

**Comment by dkebler** [comment]
Just upgraded to 1.10 so having same issue.  Did as @graywithanA suggested and no love.  No bar icons below, does not launch from packages menu nor shortcuts.   On linux ubuntu 14.04 box.

**Comment by signothefish** [comment]
Same as dkeblem, no dice with files from @graywithanA.  Windws 7.

**Comment by sebfindling** [comment]
seriously how can they not give a thing about this and fix it in so many days

**Comment by 3DEsprit** [comment]
I agree. I would think they would at the very least commit the workaround.

**Comment by graywithanA** [comment]
Sorry to hear those files aren't working for everyone.  As for the lack of a new commit.  I think I read somewhere that this package isn't supported anymore.  Am I making that up or does that sound familiar to anyone else?

**Comment by signothefish** [comment]
I think that's a safe assumption, seeing the most recent activity from this author was on 11/26/2015: https://github.com/jeremyramin

**Comment by 3DEsprit** [comment]
Unfortunately, dropping already compiled node_modules isn't going to work for everyone, as they are made for and individual system and the host OS. On the bright side, you can still install @graywithanA's package, remove the node_modules directory, and use something like [shrinkwrap](https://github.com/cortexjs/cortex-shrinkwrap) to lock the pacakge dep versions, and run _npm i_. This will give you the same setup, but with your own personal node_modules for your system. 

If there are OSX users still without Terminal Plus, I'll be happy to find out the breaking changes in that build as well. 

At the very least we can continue to use a workaround until someone picks the project back up, or forks it.

**Comment by dkebler** [comment]
someone has forked this repo and kept up to date.  Try
https://atom.io/packages/platformio-ide-terminal
or
https://atom.io/packages/terminal-fusion
I tried the former and it's working fine in 1.10 and ubuntu 14.04

**Comment by EQuimper** [comment]
Thank you @dkebler I use now [platformio-ide](https://atom.io/packages/platformio-ide-terminal) and his working like a charm

**Comment by 3DEsprit** [comment]
Thank a lot @dkebler ! 

I'm loving Terminal Fusion! Terminal Labels, Color Coding, link terminals to folders, and even inject commands to terminals. Way too cool, and extremely helpful! 

What's funny is that it's a fork of platform-ide. :laughing:

**Comment by swapnilchincholkar** [comment]
Solution at [321](https://github.com/jeremyramin/terminal-plus/issues/321)  worked for me.

**Comment by X0rg** [comment]
Thank you @dkebler, terminal-fusion works like a charm. :smile:
