### ISSUE TITLE
don't force to rebuild packages on every update

### ISSUE THREAD

**Issue by yoorek** [jeremyramin/terminal-plus#36]
it would be nice if terminal-plus did not force atom to rebuild packages and restart on every update (which is quite often)

**Comment by jeremyramin** [comment]
@yoorek My apologies, I realize I have been releasing a lot of updates lately. If it were up to me I would not have Atom rebuild Terminal-Plus every time. Atom is actually the one that thinks that Terminal-Plus needs to be rebuilt every time I release an update. I need to figure out why this happens and fix it, or let the Atom team know so they can fix it on their end.

**Comment by origin1tech** [comment]
I'm assuming the rebuild simply re-installs the npm packages so I'm guessing all its's doing is re-pulling the pty.js file which is the offender btw. Don't know enough about how Atom handles its published packages but this is what appears to be happening. Some how on the upgrade the pty.js package is not getting updated it can't find it when Atom spins back up and hence the need for rebuild. You may already know all this but thought I'd chime in to be certain.

**Comment by jeremyramin** [comment]
@origin1tech Thank you. I am aware that this is caused by the pty.js dependency that relies on native modules.

> I'm assuming the rebuild simply re-installs the npm packages so I'm guessing all its's doing is re-pulling the pty.js file which is the offender btw. Don't know enough about how Atom handles its published packages but this is what appears to be happening. Some how on the upgrade the pty.js package is not getting updated it can't find it when Atom spins back up and hence the need for rebuild.
You are right. Every update to Terminal-Plus, Atom will call call `npm install` on the dependencies to update them. I realize that this is a frustrating issue so I will get fixed as soon as possible

**Comment by origin1tech** [comment]
Right, I figured as much, that you were aware that is. think the key thing and now that I read back my post I should have been more clear. I was more or less chiming in so that others might have an understanding of what was transpiring and that since this relies on the native mod. it may be a bit tougher task to resolve than just some typical package if that makes sense. 

In the meantime I would say you should put a sticky at the top of your readme indicating this is a known issue. If new to Atom this will trip ppl up. I get asked “hey what package is that you’re using” they install about 30 min. later I get the email “it’s not working” lol. For the love of god sparing me that email ha ha!!!

In all seriousness this is a killer module. Coming from say JetBrains & IntelliJ or Webstorm having a terminal is like deal breaker if not available. T-Plus is the cleanest of the terminal pkgs IMO.

Meaning if the worst thing is needing to rebuild on updates I’m entirely cool with that. Again though I’d pop that in the top of the Readme.md so everyone knows. Most of the guys using Atom are not Node rookies so they’ll understand exactly what’s up. Just lookin’ out here...

**Comment by origin1tech** [comment]
btw have you tried simply adding a postnatal script? 

     { scripts: { “postinstall”: “node-gyp rebuild” } }

wonder if Atom would respect that. I simply don’t know. 

If not this may be difficult to fix because I don’t really see much control for the dev in the upgrade/install process itself within Atom. At least not in the API docs.

anyway just though I’d mention the post install used it before works fine for a lot of scenarios.

**Comment by jeremyramin** [comment]
> In the meantime I would say you should put a sticky at the top of your readme indicating this is a known issue. If new to Atom this will trip ppl up. I get asked “hey what package is that you’re using” they install about 30 min. later I get the email “it’s not working” lol. For the love of god sparing me that email ha ha!!!

Funnily enough, that would save me an email or two as well. I will add a warning to the README that links to here.

> In all seriousness this is a killer module. Coming from say JetBrains & IntelliJ or Webstorm having a terminal is like deal breaker if not available. T-Plus is the cleanest of the terminal pkgs IMO.
Thank you, that means a lot.

> btw have you tried simply adding a postnatal script?
     { scripts: { “postinstall”: “node-gyp rebuild” } }
wonder if Atom would respect that. I simply don’t know.

I have not tried this. I will have to get on a computer that doesn't have the requirements for node-gyp to test different script settings. Computers that can build the pty.js dependency don't see this issue.

**Comment by origin1tech** [comment]
lol that’s the very reason I didn’t just test it for you ha ha. 

Regards,

Carey Hazelton
chazelton@origin1.com <mailto:chazelton@origin1.com>
Confidentiality Notice: The information contained in this electronic transmission, is privileged and confidential and is intended only for the recipient(s) named above. If the reader of this message is not the recipient(s) named above, or an authorized agent of such recipient(s) responsible for delivering it to the intended recipient(s), you are hereby notified that you have received this electronic transmission in error. Any review, dissemination, distribution, or copying of this electronic transmission including any attachments is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately. Origin1 Technologies.

**Comment by jeremyramin** [comment]
Apparently, Atom stores the location of every compiled node file in my dependencies... Including the ones from other operating systems that I provide. Then it attempts to require every single one of these native modules and when it fails to do so it asks people to rebuild Terminal-Plus. I'm currently in the process of fixing this.

**Comment by jeremyramin** [comment]
v0.9.1 should fix this issue. If you still experience this issue, then Atom may have needed this update to adjust to the new locations of the prebuild binaries. I'll leave this issue open just incase the issue persists for the next release. If it does, then people will need  to reinstall Terminal-Plus to get rid of it.

**Comment by yoorek** [comment]
just updated with v0.9.1 and it worked smoothly - terminal-plus available right after update (was disabled before), no rebuild forced by atom, no restart. Thanks!

**Comment by jeremyramin** [comment]
Oh good! That's truly great to hear. Thanks for sticking with Terminal-Plus despite the issue.

**Comment by jeremyramin** [comment]
This issue has been resolved as of v0.9.0
