### ISSUE TITLE
View-maximize failure with Vertical File Tabs

### ISSUE THREAD

**Issue by suzetmk** [jeremyramin/terminal-plus#48]
Hi.
I'm a newbie about atom, but now I'm a junkie of atom and this wondorful plugin.

So, my problem is:
with following "Vertical File Tabs in Atom" style,
Terminal-Plus's maximize/normal view changing doesn't work correctly.

Vertical File Tabs in Atom
https://gist.github.com/jasesmith/114da4e5310eda6238f0
 
![replication](https://cloud.githubusercontent.com/assets/14934122/10682785/292db258-7975-11e5-8573-5c098b4f19f2.gif)

Atom Version: 1.1.0-beta.0-ad60d7b
Terminal-plus Version: 0.11.1
OS: Ubuntu

**Comment by jeremyramin** [comment]
@suzetmk Thank you for reporting this. I'll take a look and notify you once I release a fixed version.

**Comment by jeremyramin** [comment]
I had a chance to look at this, so I'll explain what is happening:

Terminal-Plus is displayed as a panel attached to the bottom of Atom. In the same plane is the section containing the tab-bar view. Atom prevents the section containing the tab-bar from shrinking below the size to display the tab-bar. This results in Terminal-Plus being stopped at the last tab in your tab-bar view. Terminal-Plus will continue to grow because it thinks it has more room (and it does). That causes the bottom of the editor to be pushed down out of sight. Not much I can do about this since this is related to how Atom displays sections of the editor.

You might want to check out issue #9. They are requesting that tabs be implemented, which would let you effectively "full screen" your terminal. If this interests you, you can comment there and I will notify everyone once an update with tabs has been released.

**Comment by suzetmk** [comment]
Thank you for your quick reply.

Yes, terminal-plus as tab should be best resolution for me.
Please continue implementation for issue #9.

**Comment by jeremyramin** [comment]
No problem, closing this issue as it is being handled by another issue.

**Comment by suzetmk** [comment]
I'm so sorry, but I had a misundersanding about what you mentioned of "terminal as a tab"...
I tried tab feature and it seems to be really nice, but unfortunately didn't fit to my use case.

I prefer to use terminal-plus with small size normally,
and to maximize/re-contract it on demand, with keeping current jobs.
(In addition, it will be nice if I can toggle maximize with command)

I tried those operations with tab-terminal and atom's pane splitting/resizing commands,
but that was really complicated...

So, I think that if I can toggle teminal between tab and bottom-tool-panel with command,
that could be an alternative for me.
Could you check to see if it's possible?

**Comment by suzetmk** [comment]
One more request,
It would be nice if atom's active tab is restored to last one 
when activated terminal-tab is switched to botom-tool-panel in above use case.

**Comment by jeremyramin** [comment]
@suzetmk I have been planning on replacing the default full screen with this tab view mode. A command for toggling "fullscreen" can be added with this update. That way you could toggle between tab view and bottom panel view.

>One more request,
It would be nice if atom's active tab is restored to last one 
when activated terminal-tab is switched to botom-tool-panel in above use case. 

Just to clarify, should the focus return to the previous active tab or to the terminal? In this instance, `in focus` implies that your typing input would go to the item that is "in focus". The difference being is that I could have the previous active tab become the active tab while keeping the terminal in focus or the previous active tab would become active and take the focus from the terminal.

Sorry for the late reply! It has been a busy week.
