### ISSUE TITLE
stay full screen if in full screen when creating new terminal

### ISSUE THREAD

**Issue by Goddard** [jeremyramin/terminal-plus#72]
Small issue and probably not even an issue just an idea of how a behavior should be.

When creating a new tab and you are already in full screen mode why doesn't it create the new tab in full screen mode as well?

Thanks for the awesome package.

**Comment by jeremyramin** [comment]
The fullscreen mode is written in a manner that makes it different for each terminal because each terminal has it's own height value. The fullscreen mode could be global, meaning that new tabs would be effected as well but then you would not be able to fullscreen some terminals while keeping others normal.

Thanks for using Terminal-Plus.

**Comment by Goddard** [comment]
Could you not just have the new tab adopt the value of the tab that is currently in focus by default?  That would be predictable behavior right?

**Comment by jeremyramin** [comment]
I could definitely add that. I'll inform you when I have a release with this implemented.

**Comment by Goddard** [comment]
awesome...
