### ISSUE TITLE
'Working Directory' set as 'Project' not working properly

### ISSUE THREAD

**Issue by nunocastromartins** [jeremyramin/terminal-plus#74]
Files from different project folders cause the terminal to open in the same path: namely, the first project folder in the tree view.

Steps to reproduce:

1. Open two project folders ("Application: Add Project Folder" action)
2. Open a file from inside each project folder
3. Create a new terminal window for each file

This might be on purpose. If it is, I don't think it is the appropriate behaviour.

**Comment by jeremyramin** [comment]
@nunocastromartins At the moment, the terminal does select from the first project folder. While this was intentional, this is mostly due to the fact that there is no command for getting the project folder from the currently open file. The good news is that I already have an idea in mind for implementing this so I'll get to work on adding it.

**Comment by jeremyramin** [comment]
Implemented as of v0.13.1.
